### ISSUE TITLE
About .github.io

### ISSUE THREAD

**Issue by skyleaworlder** [Kerr0220/Kerr0220.github.io#1]
虽然 [官方文档](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages) 没有规定，但个人以为，`<username>.github.io` 一般作为 “用户个人站点” 使用。

😄 并非只有 `<username>.github.io`  才可以激活 `GitHub Page Environment`。一般项目也可以通过 `GitHub Page` 架设网页到 `<username>.github.io` 之下：[Configuring a publishing source for your GitHub Pages site](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source).

**Comment by Kerr0220** [comment]
好的，感谢提醒🙏。
这个项目是课程作业，当初部署的时候是为了方便老师检查，因而部署在了`<username>.github.io`下。
